apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "frontend-golden-path-api"
  namespace: "frontend-golden-path"
  labels:
    "team": "frontend-golden-path"
spec:
  image: {{ image }}
  port: 3000
  liveness:
    path: "/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/isAlive"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 128Mi
  ingresses:
    - https://frontend-golden-path-api.intern.dev.nav.no
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: frontend-golden-path
  idporten:
    enabled: true


