name: Build & Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # ratchet:actions/checkout@v4
        with:
          persist-credentials: false
      - name: Push docker image to GAR
        uses: nais/docker-build-push@main # ratchet:exclude
        id: docker-build-push
        with:
          team: frontend-golden-path
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Deploy
        uses: nais/deploy/actions/deploy@v2 # ratchet:exclude
        env:
          CLUSTER: dev-gcp
          IMAGE: ${{ steps.docker-build-push.outputs.image }}
          RESOURCE: nais.yaml
